# -------------------------------
# Basic configs
# -------------------------------
TOP       = dot_product
BUILDDIR  = build

# -------------------------------
# Sources
# -------------------------------
SRCS      = rtl/*.sv
TB        = tb/tb_$(TOP).sv
LPF 	  = fpga/$(TOP).lpf

include rules.mk